---
title: "About"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## GitHub

[https://github.com/JulianHabermann/Final-Project-Working.git](https://github.com/JulianHabermann/Final-Project-Working.git)

## Background

This project will analyze admissibility data from immigrants from different countries across different time periods. The purpose of this analysis is to help demonstrate the number of immigrants who are denied from the US every year as well as where they come from. Too often, immigration is treated as waiting in line when hundreds of thousands of people are barred from that line to begin with. 

I chose this project for a couple of reasons. First, I am interested in immigration data and studied ineligibilities extensively last year for high school debate. I have a strong knowledge of the legal basis of these exclusions but do not know much about the data. Second, immigration data is quite accessible, but it is too often analyzed in a very standard manner. This project allows for a unique angle on a pertinent issue. Finally, I would be able to do historical analysis of ineligbilities over time which I have not seen elsewhere. Furthermore, the ability to create customization would have been so useful for me as a student that I hope to create a tool to perform this analysis with ease. 

## The Data

In order to create this visualization, I will combine multiple DHS public excel files that show the number of ineligibilities from different countries across time periods. I hope to create a couple of graphs from the data. First, a comparison between ineligiblities and admission to demonstrate the acceptance gap. Second, a historical analysis of ineligibilities over time. Finally, a country-based analysis will be included, probably through an exploratory tool. 

Luckily, this data is accessible, relatively clean, and very usable to begin with. This data with additional cleaning is attached in the github link above. 

The second source of data has introduced more complications for my ability to gather. This data set was going to be a separate State Department table of the categories that cause ineligibilities. Luckily, the data for the period of 2009-2018 is all publicly available. The only problem is that I have only been able to find the data as a pdf. For this milestone, I first looked for the data as an excel document, but extensive searching left me empty-handed. Next, I tried to find a method to convert pdfs into data in R. The tools that I found online can only be described as weak for doing this process quickly. 

Still, I have hope that this data source will be usable. First, I am going to try to find a contact to request the data as an excel document. Knowing the government, it probably will not work. So, I am going to figure out the quickest method to transcribe this data. There are so many methods of converting pdf data that I am certain that I will not have to transcribe the many rows by hand. 


## About Me

My name is Julian Habermann, and I am a first-year in Thayer. I am heavily involved with college policy debate (the speed talking kind) and am pretty good at Smash Bros. 
